name: Python application test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest tests/ --headless=yes --browser=chrome

      - name: Generate Allure report
        run: |
          allure generate allure_logs -o allure-report
        continue-on-error: true

      - uses: actions/upload-artifact@v2
        with:
          name: Allure Results
          path: allure-report/

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Screenshots
          path: screenshots/
          if-no-files-found: ignore
