name: Python application test

on:
  workflow_dispatch:
    inputs:
      test-path:
        description: 'Test path (e.g., tests/tests_ui/tests_21vek.py)'
        required: true
        default: 'tests/'
      headless:
        description: 'Run headless? (yes or no)'
        required: true
        default: 'yes'
      browser:
        description: 'Browser (chrome or firefox)'
        required: true
        default: 'chrome'

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Add module to PYTHONPATH
        run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest ${{ github.event.inputs.test-path }} --headless=${{ github.event.inputs.headless }} --browser=${{ github.event.inputs.browser }}

      - name: Generate Allure report
        run: allure generate allure_logs -o allure-report
        continue-on-error: true

      - uses: actions/upload-artifact@v2
        with:
          name: Allure Results
          path: allure-report/

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Screenshots
          path: screenshots/
          if-no-files-found: ignore
